/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_reservasi;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Reza Siahaan
 */
public class menuUtama extends javax.swing.JFrame {
    Connection con;
    Statement stat, stat1;
    ResultSet rs, rs1, rs2;
    String sql;
    PreparedStatement pst;
    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        initComponents();
        koneksiDB DB = new koneksiDB();
        DB.config();
        con = koneksiDB.conn;
        stat = koneksiDB.stmt;
        show_kamar();
        show_pesanan();
    }
    public ArrayList<kamar> kamarList(String query){
        ArrayList<kamar> kamarList = new ArrayList<>();
        try{
            stat = con.createStatement();
            rs = stat.executeQuery(query);
            kamar Kamar;
            
            while(rs.next()){
                Kamar = new kamar(rs.getString("id_kamar"), rs.getString("tipe_kamar"),rs.getString("tarif"),rs.getInt("status_ruangan"));
                kamarList.add(Kamar);
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        return kamarList;
    }
    public void show_kamar(){
        String query1 = "SELECT id_kamar, tipe_kamar, tarif, status_ruangan FROM kamar";
        ArrayList<kamar> list = kamarList(query1);
        DefaultTableModel model = (DefaultTableModel)jTableDaftarKamar.getModel();
        Object[] row = new Object[5];
        for(int i=0; i<list.size();i++){
            row[0]= list.get(i).getIdKamar();
            row[1]= list.get(i).getTipeKamar();
            row[2]= list.get(i).getTarif();
            row[3]= list.get(i).getStatusRuangan();
            ////row[4]= list.get(i).getKodeReceptionist();
            model.addRow(row);
        }
    }
    public ArrayList<Pesanan> pesananList(String query){
        ArrayList<Pesanan> pesananList = new ArrayList<>();
        try{
            stat = con.createStatement();
            rs = stat.executeQuery(query);
            Pesanan pesanan;
            while(rs.next()){
                int id_pesanan= rs.getInt("id_pesanan");
                String id_kamar= rs.getString("id_kamar");
                String email= rs.getString("email");
                int lama_nginap= rs.getInt("lama_nginap");
                pesanan = new Pesanan(id_pesanan,id_kamar,email,lama_nginap);
                
                pesananList.add(pesanan);
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        return pesananList;
    }
    public void show_pesanan(){
        String query1 = "SELECT * FROM pesanan";
        ArrayList<Pesanan> list = pesananList(query1);
        DefaultTableModel model = (DefaultTableModel)jTabelPesanan.getModel();
        Object[] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]= list.get(i).getIdPesanan();
            row[1]= list.get(i).getIdKamar();
            row[2]= list.get(i).getEmail();
            row[3]= list.get(i).getLamaNginap();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jRiwayatPesanan = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDaftarKamar = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabelPesanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDropDownTipe = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDropDownStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TextIdKamar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLamaNginap = new javax.swing.JTextField();
        jPesanKamarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jHapusField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jHapusBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jUbahIdPesanField = new javax.swing.JTextField();
        jUbahBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jUbahIdKamarField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLamaNginapField = new javax.swing.JTextField();
        jCariJenisKamar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("tab1", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableDaftarKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Kamar", "Tipe Kamar", "Harga", "Status"
            }
        ));
        jScrollPane3.setViewportView(jTableDaftarKamar);

        jRiwayatPesanan.addTab("Daftar Kamar", jScrollPane3);

        jTabelPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pesanan", "Id Kamar", "Email", "Lama Nginap"
            }
        ));
        jScrollPane4.setViewportView(jTabelPesanan);

        jRiwayatPesanan.addTab("Pesanan", jScrollPane4);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Menu Utama");

        jDropDownTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Deluxe" }));
        jDropDownTipe.setToolTipText("");
        jDropDownTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDropDownTipeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cari Kamar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tipe Kamar");

        jDropDownStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Booked", "Not Booked" }));
        jDropDownStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDropDownStatusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Status Ruangan");

        TextIdKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdKamarActionPerformed(evt);
            }
        });

        jLabel2.setText("Id Kamar");

        jLabel3.setText("Lama Nginap");

        jPesanKamarBtn.setText("Pesan Kamar");
        jPesanKamarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesanKamarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLamaNginap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextIdKamar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPesanKamarBtn, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextIdKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamaNginap, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPesanKamarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Pesan Kamar", jPanel1);

        jLabel7.setText("Id Pesanan");

        jHapusBtn.setText("Hapus");
        jHapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Id Pesanan");

        jUbahBtn.setText("Ubah");
        jUbahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUbahBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Ubah Pesanan");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Hapus Pesanan");

        jLabel11.setText("Id Kamar");

        jLabel12.setText("Lama Nginap");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(139, 139, 139))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(87, 87, 87))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jHapusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jHapusField)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addGap(62, 62, 62)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jUbahIdKamarField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jUbahIdPesanField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLamaNginapField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jUbahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUbahIdPesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUbahIdKamarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamaNginapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jUbahBtn)
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHapusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHapusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Pesanan", jPanel2);

        jCariJenisKamar.setText("Cari");
        jCariJenisKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCariJenisKamarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addComponent(jDropDownTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(jDropDownStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCariJenisKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRiwayatPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jTabbedPane1)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(408, 408, 408))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jDropDownStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jCariJenisKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jDropDownTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRiwayatPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdKamarActionPerformed

    private void jDropDownTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDropDownTipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDropDownTipeActionPerformed

    private void jDropDownStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDropDownStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDropDownStatusActionPerformed

    private void jHapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusBtnActionPerformed
        // TODO add your handling code here:
        
        try{
            String hapus = jHapusField.getText();
            
            String query= "DELETE FROM pesanan WHERE  id_pesanan = '"+hapus+"'";
            pst = con.prepareStatement(query);
            pst.execute();
            
        }catch(Exception e){
            jOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jHapusBtnActionPerformed

    private void jCariJenisKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCariJenisKamarActionPerformed
        // TODO add your handling code here:
        String standardNotBooked = "SELECT id_kamar,tipe_kamar,tarif,status_ruangan FROM kamar WHERE tipe_kamar = 'standard' AND status_ruangan='0'";
        String standardBooked = "SELECT id_kamar,tipe_kamar,tarif,status_ruangan FROM kamar WHERE tipe_kamar = 'standard' AND status_ruangan='1'";
        String deluxeNotBooked = "SELECT id_kamar,tipe_kamar,tarif,status_ruangan FROM kamar WHERE tipe_kamar = 'deluxe' AND status_ruangan='0'";
        String deluxeBooked = "SELECT id_kamar,tipe_kamar,tarif,status_ruangan FROM kamar WHERE tipe_kamar = 'deluxe' AND status_ruangan='1'";
        
        
        ArrayList<kamar> kStandardNot = kamarList(standardNotBooked);
        ArrayList<kamar> kStandardBooked = kamarList(standardBooked);
        ArrayList<kamar> kDeluxeNot = kamarList(deluxeNotBooked);
        ArrayList<kamar> kDeluxeBooked = kamarList(deluxeBooked);
        DefaultTableModel model = (DefaultTableModel)jTableDaftarKamar.getModel();
        
        
        
        String tipeKamar = jDropDownTipe.getSelectedItem().toString();
        String status = jDropDownStatus.getSelectedItem().toString();
        System.out.println(tipeKamar);
        System.out.println(status);
        Object[] row = new Object[4];
        model.setRowCount(0);
        try{
            if(tipeKamar == "Standard" && status == "Booked") {
                for(int i=0; i<kStandardBooked.size();i++){
                    row[0]= kStandardBooked.get(i).getIdKamar();
                    row[1]= kStandardBooked.get(i).getTipeKamar();
                    row[2]= kStandardBooked.get(i).getTarif();
                    row[3]= kStandardBooked.get(i).getStatusRuangan();
                    model.addRow(row);
                }
            }
            else if(tipeKamar == "Standard" && status == "Not Booked"){
                for(int i=0; i<kStandardNot.size();i++){
                    row[0]= kStandardNot.get(i).getIdKamar();
                    row[1]= kStandardNot.get(i).getTipeKamar();
                    row[2]= kStandardNot.get(i).getTarif();
                    row[3]= kStandardNot.get(i).getStatusRuangan();
                    model.addRow(row);
                }
            }
            else if(tipeKamar == "Deluxe" && status == "Booked"){
                for(int i=0; i<kDeluxeNot.size();i++){
                    row[0]= kDeluxeBooked.get(i).getIdKamar();
                    row[1]= kDeluxeBooked.get(i).getTipeKamar();
                    row[2]= kDeluxeBooked.get(i).getTarif();
                    row[3]= kDeluxeBooked.get(i).getStatusRuangan();
                    model.addRow(row);
                }
            }
            else if(tipeKamar == "Deluxe" && status == "Not Booked"){
                for(int i=0; i<kDeluxeNot.size();i++){
                    row[0]= kDeluxeNot.get(i).getIdKamar();
                    row[1]= kDeluxeNot.get(i).getTipeKamar();
                    row[2]= kDeluxeNot.get(i).getTarif();
                    row[3]= kDeluxeNot.get(i).getStatusRuangan();
                    model.addRow(row);
                }
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
            
    }//GEN-LAST:event_jCariJenisKamarActionPerformed

    private void jPesanKamarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesanKamarBtnActionPerformed
        // TODO add your handling code here:
        
        
        try{
            String idKamar = TextIdKamar.getText();
            String lama = jLamaNginap.getText();
            int lamaNginap = Integer.parseInt(lama);
            
            String query = "INSERT INTO pesanan VALUES (4,'"+idKamar+"','test123@gmail.com','"+lamaNginap+"');";
            pst = con.prepareStatement(query);
            pst.execute();
            
        }catch(Exception e){
            jOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jPesanKamarBtnActionPerformed

    private void jUbahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUbahBtnActionPerformed
        // TODO add your handling code here:
        
        
        try{
            String sIdPesanan= jUbahIdPesanField.getText();
            int idPesanan = Integer.parseInt(sIdPesanan);
            
            String idKamar= jUbahIdKamarField.getText();
            String lama= jLamaNginapField.getText();
            int lamaNginap = Integer.parseInt(lama);
            
            String query = "UPDATE pesanan SET id_kamar = '"+idKamar+"',lama_nginap='"+lamaNginap+"' WHERE id_pesanan = '"+idPesanan+"';";
            pst = con.prepareStatement(query);
            pst.execute();
            
        }catch(Exception e){
            jOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jUbahBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextIdKamar;
    private javax.swing.JButton jCariJenisKamar;
    private javax.swing.JComboBox<String> jDropDownStatus;
    private javax.swing.JComboBox<String> jDropDownTipe;
    private javax.swing.JButton jHapusBtn;
    private javax.swing.JTextField jHapusField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLamaNginap;
    private javax.swing.JTextField jLamaNginapField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jPesanKamarBtn;
    private javax.swing.JTabbedPane jRiwayatPesanan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTabelPesanan;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableDaftarKamar;
    private javax.swing.JButton jUbahBtn;
    private javax.swing.JTextField jUbahIdKamarField;
    private javax.swing.JTextField jUbahIdPesanField;
    // End of variables declaration//GEN-END:variables
}
